### ISSUE TITLE
无重码时五笔输入无法自动上屏

### ISSUE THREAD

**Issue by shuxiao9058** [tumashu/liberime#1]
如题，五笔输入自动上屏有问题，比如一个词语：“关系”，当输入”mexl“时，没有任何候选项。

出问题的schema文件配置：
``` yaml
speller:
   max_code_length: 4 
   auto_select: true 
   auto_select_unique_candidate: true 
```

当为如下配置时，则正常：
``` yaml
speller:
   max_code_length: 4
   auto_select: false
   auto_select_unique_candidate: false

```
